yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Имя')
    slug = models.SlugField(unique=True, verbose_name='Адрес')
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        default_related_name = 'posts'
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        TEXT_LENGTH = 15
        return self.text[:TEXT_LENGTH]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        ordering = ['-created']
        default_related_name = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        TEXT_LENGTH = 15
        return self.text[:TEXT_LENGTH]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор подписки',
        related_name='following'
    )

    def __str__(self):
        return f'Подписка {self.user} на {self.author}'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст',
            'group': 'Группа'
        }
        help_texts = {
            'group': 'Группа, к которой будет относиться пост'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Напишите свой комментарий'
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from django.shortcuts import redirect
from django.conf import settings

CACHE_UPDATE_FREQUENCY = 20


def paginator(posts, request):
    """Формирует страницу с постами"""
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(CACHE_UPDATE_FREQUENCY, key_prefix='index_page')
def index(request):
    """Главная страница"""
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    post_list = Post.objects.select_related('author').all()
    page_obj = paginator(post_list, request)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Страница постов группы"""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author').all()
    page_obj = paginator(post_list, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Страница польователя"""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginator(post_list, request)
    following = False
    if request.user.is_authenticated:
        if Follow.objects.filter(user=request.user).filter(author=author):
            following = True
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,

    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Страница поста"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = post.comments.select_related('author').all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Создание нового поста"""
    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
        )
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:profile', request.user.username)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post_id': post_id,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """Создание комментария к посту"""
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Станица подписок"""
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj,
        'title': f'Подписки пользователя {request.user}'
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Создание подписки"""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Удаление подписки"""
    author = get_object_or_404(User, username=username)
    follow = get_object_or_404(Follow, author=author, user=request.user)
    follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
  Редактировать запись
  {% else %}
  Добавить запись
  {% endif %}
{% endblock %} 
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
        {% load user_filters %}
          {% if form.errors %}
              {% for field in form %} 
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          {% if is_edit %}
            <form method="post" enctype="multipart/form-data">
          {% else %}
            <form method="post" enctype="multipart/form-data">
          {% endif %}
            {% csrf_token %}
            {% for field in form %} 
              <div class="form-group row my-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
                    <small 
                       id="{{ field.id_for_label }}-help"
                       class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% include 'posts/index.html' %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group }}
{% endblock %} 
{% block content %}
  <h1>{{ group }}</h1>
  <p>{{ group.description}}</p>
  {% for post in page_obj %}
    {% include 'posts/includes/posts_display.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{title}}
{% endblock %} 
{% block content %}
  <h1>{{title}}</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/posts_display.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
  Пост {{post|truncatechars:30}}
{% endblock %} 
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{post.group}} <br>
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {% firstof post.author.get_full_name post.author.username %}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
              <p>
               {{ comment.text }}
              </p>
            </div>
          </div>
      {% endfor %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {% firstof author.get_full_name author.username %}
{% endblock %} 
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {% firstof author.get_full_name author.username %} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% if author != user %}
    {% if user.is_authenticated %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
    {% endif %}
    {% endif %}
    {% for post in page_obj %}
      {% include 'posts/includes/posts_display.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}